-- rose axe
STRINGS.NAMES.ROSEAXE = '玫瑰斧'
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROSEAXE = '用玫瑰精油保养'
STRINGS.RECIPE_DESC.ROSEAXE = '拿起来也优雅'

-- rose gun flag
STRINGS.NAMES.ROSEGUNFLAG = "玫瑰枪旗"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROSEGUNFLAG = "玫瑰的香气振奋人心"
STRINGS.RECIPE_DESC.ROSEGUNFLAG = "高贵之旗闪耀勇气"

-- rose scissors
STRINGS.NAMES.ROSESCISSORS = "玫瑰剪刀"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROSESCISSORS = "该修修我的花圃了。"
STRINGS.RECIPE_DESC.ROSESCISSORS = "巨大而锋利。"

-- rose parasol
STRINGS.NAMES.ROSEPARASOL = "玫瑰伞"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROSEPARASOL = "希望别太热。"
STRINGS.RECIPE_DESC.ROSEPARASOL = "行走在海面之上。"

-- rose frost wand
STRINGS.NAMES.ROSEFROSTWAND = "玫瑰霜杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROSEFROSTWAND = "散发着冰冷的气息。"
STRINGS.RECIPE_DESC.ROSEFROSTWAND = "冬日里的第一朵玫瑰。"

-- ocean trident
STRINGS.NAMES.OCEANTRIDENT = "海洋三叉戟"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANTRIDENT = "向海而战。"
STRINGS.RECIPE_DESC.OCEANTRIDENT = "海面上的雷鸣之矛。"

-- crow scythe
STRINGS.NAMES.CROWSCYTHE = "乌鸦镰刀"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CROWSCYTHE = "刀刃中仿佛回响着黑羽的低语。"
STRINGS.RECIPE_DESC.CROWSCYTHE = "让乌鸦回应每一次挥舞。"

-- nature tools wand
STRINGS.NAMES.NATURETOOLSWAND = "自然法杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NATURETOOLSWAND = "一杖在手，采集与作业都能完成。"
STRINGS.RECIPE_DESC.NATURETOOLSWAND = "自然之力凝成的工具法杖。"
